version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - MAX_CONNECTIONS=50
    networks:
      - keycloak

  keycloak:
    image: williamokano/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=changeit
      - POSTGRES_PORT_5432_TCP_ADDR=postgres
    depends_on:
      - postgres
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/16
